routes/web.php
<?php
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('layouts.web');
// });
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('config:clear');
    return '<h1>Cache facade value cleared</h1>';
    // return what you want
});

Route::any('/','WebController@index')->name('web');
Route::any('/about-us','WebController@about')->name('aboutus');
Route::any('/contact-us','WebController@contactus')->name('contactus');
Route::any('/enquiry','WebController@enquiry')->name('enquiry');
Route::any('/storecontactus','WebController@storecontactus')->name('storecontactus');
Route::any('/storeenquiry','WebController@storeenquiry')->name('storeenquiry');
Route::any('/product/{id}','WebController@listing')->name('listing');
Route::any('/detail/{id}','WebController@detail')->name('detail');

Route::group(['prefix' => 'admin'],function () {
	Auth::routes();
   	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories','CategoryController');
	Route::resource('products','ProductController');
	Route::resource('pages','PageController');
	Route::get('subcat','CategoryController@subcat')->name('subcat');
	Route::any('contact-us','HomeController@contactUs')->name('contactlist');
	Route::any('enquiry','HomeController@enquiry')->name('enquiryform');
	Route::any('changelistingstatus','ProductController@changelistingstatus')->name('changelistingstatus');
	Route::any('changebrandingstatus','ProductController@changebrandingstatus')->name('changebrandingstatus');
	Route::any('categorylistingstatus','CategoryController@categorylistingstatus')->name('categorylistingstatus');
});

resources/views/inc/css.blade.php
<link rel="stylesheet" href="{{ asset('vendors/mdi/css/materialdesignicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendors/css/vendor.bundle.base.css') }}">
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

resources/views/inc/footer.blade.php
<footer class="footer">
	<div class="d-sm-flex justify-content-center justify-content-sm-between">
	  <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021 <a href="https://www.bootstrapdash.com/" target="_blank">Rsons</a>. All rights reserved.</span>
	  <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Novex <i class="mdi mdi-heart text-danger"></i></span>
	</div>
</footer>

resources/views/inc/header.blade.php
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand brand-logo" href="{{route('home')}}"><img src="{{ asset('web/images/logo3.png') }}" style="height: 70px;" height="70px" alt="logo" /></a>
    <a class="navbar-brand brand-logo-mini" href="{{route('home')}}">Novex</a>
  </div>
  <div class="navbar-menu-wrapper d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span> 
    </button>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <div class="nav-profile-img">
            <img src="{{ asset('images/faces/face1.jpg') }}" alt="image">
            <span class="availability-status online"></span>
          </div>
          <div class="nav-profile-text">
            <p class="mb-1 text-black">Admin</p>
          </div>
        </a>
        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
          
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
            <i class="mdi mdi-logout mr-2 text-primary"></i> Signout </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
      <span class="mdi mdi-menu"></span>
    </button>
  </div>
</nav>

resources/views/inc/js.blade.php
<script src="{{ asset('vendors/js/vendor.bundle.base.js') }}"></script>
<script src="{{ asset('vendors/chart.js/Chart.min.js') }}"></script>
<script src="{{ asset('js/off-canvas.js') }}"></script>
<script src="{{ asset('js/hoverable-collapse.js') }}"></script>
<script src="{{ asset('js/misc.js') }}"></script>
<script src="{{ asset('js/dashboard.js') }}"></script>
<script src="{{ asset('js/todolist.js') }}"></script>
<script src="{{ asset('js/file-upload.js') }}"></script>

resources/views/inc/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <ul class="nav">



    <li class="nav-item">
      <a class="nav-link" href="{{route('home')}}">
        <span class="menu-title">Dashboard</span>
        <i class="mdi mdi-home menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('categories.index')}}">
        <span class="menu-title">Categories</span>
        <i class="mdi mdi-crosshairs-gps menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('products.index')}}">
        <span class="menu-title">Products</span>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('contactlist')}}">
        <span class="menu-title">Contact Us List</span>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{route('enquiryform')}}">
        <span class="menu-title">Enquiry Form List</span>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
    </li>


    <!-- <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-category" aria-expanded="false" aria-controls="ui-category">
        <span class="menu-title">Category</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-crosshairs-gps menu-icon"></i>
      </a>
      <div class="collapse" id="ui-category">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ route('categories.index') }}">Listing</a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ route('categories.create') }}">Add category</a></li>
        </ul>
      </div>
    </li>

    <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-products" aria-expanded="false" aria-controls="ui-products">
        <span class="menu-title">Products</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-medical-bag menu-icon"></i>
      </a>
      <div class="collapse" id="ui-products">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ route('products.index') }}"> Listing </a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ route('products.create') }}"> Add Product </a></li>
        </ul>
      </div>
    </li> -->

    <!-- <li class="nav-item">
      <a class="nav-link" data-toggle="collapse" href="#ui-pages" aria-expanded="false" aria-controls="ui-pages">
        <span class="menu-title">Pages</span>
        <i class="menu-arrow"></i>
        <i class="mdi mdi-format-list-bulleted menu-icon"></i>
      </a>
      <div class="collapse" id="ui-pages">
        <ul class="nav flex-column sub-menu">
          <li class="nav-item"> <a class="nav-link" href="{{ route('pages.index') }}">Listing</a></li>
          <li class="nav-item"> <a class="nav-link" href="{{ route('pages.index') }}">Add Pages</a></li>
        </ul>
      </div>
    </li> -->

  </ul>
</nav>