routes/web.php
<?php
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('layouts.web');
// });
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('config:clear');
    return '<h1>Cache facade value cleared</h1>';
    // return what you want
});

Route::any('/','WebController@index')->name('web');
Route::any('/about-us','WebController@about')->name('aboutus');
Route::any('/contact-us','WebController@contactus')->name('contactus');
Route::any('/enquiry','WebController@enquiry')->name('enquiry');
Route::any('/storecontactus','WebController@storecontactus')->name('storecontactus');
Route::any('/storeenquiry','WebController@storeenquiry')->name('storeenquiry');
Route::any('/product/{id}','WebController@listing')->name('listing');
Route::any('/detail/{id}','WebController@detail')->name('detail');

Route::group(['prefix' => 'admin'],function () {
	Auth::routes();
   	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories','CategoryController');
	Route::resource('products','ProductController');
	Route::resource('pages','PageController');
	Route::get('subcat','CategoryController@subcat')->name('subcat');
	Route::any('contact-us','HomeController@contactUs')->name('contactlist');
	Route::any('enquiry','HomeController@enquiry')->name('enquiryform');
	Route::any('changelistingstatus','ProductController@changelistingstatus')->name('changelistingstatus');
	Route::any('changebrandingstatus','ProductController@changebrandingstatus')->name('changebrandingstatus');
	Route::any('categorylistingstatus','CategoryController@categorylistingstatus')->name('categorylistingstatus');
});

resources/views/pages/create.blade.php
@extends('layouts.admin')
@section('content')

    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> Add Category </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Category</li>
              <li class="breadcrumb-item active" aria-current="page">Add Category</li>
            </ol>
          </nav>
        </div>

        @if ($errors->any())
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    
                    <form action="{{ route('categories.store') }}" method="POST">
                    @csrf

                      <div class="form-group">
                        <label for="exampleSelectcategory">Parent Category</label>
                        <select class="form-control" id="exampleSelectcategory" name="parent_id">
                            <option value="">Select Parent Category</option>
                            @foreach($catListing as $key=>$val)
                                <option value="{{$key}}">{{$val}}</option>
                            @endforeach
                        </select>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Name </label>
                        <input type="text" class="form-control" id="exampleInputName1" required="required" placeholder="Name" name="name">
                      </div>

                      <div class="form-group">
                        <label for="exampleSelectstatus"><span style="color: red;">*</span> Status </label>
                        <select class="form-control" id="exampleSelectstatus" required="required" name="status">
                          <option value="1">Active</option>
                          <option value="0">Inactive</option>
                        </select>
                      </div>
                      
                      <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                      <a href="{{route('categories.index')}}" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
          </div>

        </div>
    </div>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.admin')
@section('content')



    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title"> Edit Category </h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Category</li>
              <li class="breadcrumb-item active" aria-current="page">Edit Category</li>
            </ol>
          </nav>
        </div>

        @if ($errors->any())
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-6 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    
                    <form action="{{ route('categories.update',$category->id) }}" method="POST">
                    @csrf
                    @method('PUT')

                      <div class="form-group">
                        <label for="exampleSelectcategory">Parent Category</label>
                        <select class="form-control" id="exampleSelectcategory" name="parent_id">
                            <option value="">Select Parent Category</option>
                            @foreach($catListing as $key=>$val)
                                <option value="{{$key}}" <?= ($category->parent_id == $key)?"Selected":""?>>{{$val}}</option>
                            @endforeach
                        </select>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputName1"><span style="color: red;">*</span> Name</label>
                        <input type="text" class="form-control" id="exampleInputName1" required="required" placeholder="Name" value="{{ $category->name }}" name="name">
                      </div>

                      <div class="form-group">
                        <label for="exampleSelectstatus"><span style="color: red;">*</span> Status</label>
                        <select class="form-control" id="exampleSelectstatus" required="required" name="status">
                          <option value="1">Active</option>
                          <option value="0">Inactive</option>
                        </select>
                      </div>
                      
                      <button type="submit" class="btn btn-gradient-primary mr-2">Submit</button>
                      <a href="{{route('categories.index')}}" class="btn btn-light">Cancel</a>
                    </form>
                </div>
            </div>
          </div>

        </div>
    </div>
    
@endsection

resources/views/pages/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
          <h3 class="page-title">Category List</h3>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Category List</li>
            </ol>
            
          </nav>
        </div>

        @if ($message = Session::get('success'))
            <div class="row">
                <div class="col-12">
                    <div class="alert alert-success">
                        <p>{{ $message }}</p>
                    </div>
                </div>
            </div>
        @endif

        <div class="row">
          <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <p class="card-description"> <a class="btn btn-success btn-sm float-sm-right" href="{{ route('categories.create') }}"> Add Category</a></p>
                
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Parent Category</th>
                      <th>Category</th>
                      <th>Status</th>
                      <th width="280px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($categories as $category)
                    <tr>
                      <td>{{ ++$i }}</td>
                      <td>{{ $catListing[$category->parent_id]??"" }}</td>
                      <td>{{ $category->name }}</td>
                      <td>
                        @if($category->status == 1)
                            <label class="badge badge-success">Active</label>
                        @else
                            <label class="badge badge-danger">In-Active</label>
                        @endif
                      </td>
                      <td>
                        <form action="{{ route('categories.destroy',$category->id) }}" method="POST">
                            <a class="btn btn-primary btn-xs" href="{{ route('categories.edit',$category->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-xs">Delete</button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
                {!! $categories->links() !!}
              </div>
            </div>
          </div>
        </div>
    </div>      
@endsection